monolog:
    handlers:
        main:
            type: 'stream'
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: 'warning'
        console:
            type: 'console'
            bubble: false
        firephp:
            type: 'firephp'
            level: 'info'
        chromephp:
            type: 'chromephp'
            level: 'info'
